// This file is intentionally without code.
// It's present so that service worker registration will work when serving from the 'app' directory.
// The version of service-worker.js that's present in the 'dist' directory is automatically
// generated by the 'generate-service-worker' gulp task, and contains code to precache resources.

/* eslint-env browser, serviceworker, es6 */

'use strict';

self.addEventListener('push', function(event) {
  console.log('[Service Worker] Push Received:', event);

  var payload;
  var defaultPayload = {
    title: 'Notificación por defecto',
    config: {
      body: 'Biko Open Space',
      icon: '/images/app-shell/master-icon.png',
      badge: '/images/app-shell/master-icon.badge.png'
    }
  };

  // Avoid errors using event.data.json()
  try {
    payload = event.data.json();
    console.log('[Service Worker] JSON payload found:', payload);
  } catch (e) {
    payload = defaultPayload;
    console.log(
      '[Service Worker] No payload found. Using default payload:',
      payload
    );
  }

  event.waitUntil(
    self.registration.showNotification(payload.title, payload.config)
  );
});

self.addEventListener('notificationclick', function(event) {
  console.log('[Service Worker] Notification click received');
  event.notification.close();
  event.waitUntil(
    clients.openWindow('https://openbiko-pwa.firebaseapp.com/')
  );
});
